server:
  port: 8081
spring:
  application:
    name: backend-config-service
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/EduardoP1907/TingesoEvaluacion2
          search-paths: "Unidad 2/MicroServicios/config-data"